name: Production

on:
  push:
    branches:
      - main
      - release-workflow

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  check_new_version:
    runs-on: ubuntu-latest
    outputs:
      new_release: ${{ steps.check-new-version.outputs.new_release }}
    steps:
      - name: Setup Nushell
        uses: hustcer/setup-nu@v3
        with:
          version: 0.100.0

      - name: Check new version
        id: check-new-version
        shell: nu {0}
        run: |
          let api_url = "https://api.github.com/repos/nonscalable/OnlyGroceries/releases/latest"
          let latest_tag = http get $api_url | get tag_name
          let package_tag = $"v(open ./package.json | get version)"
          let new_version = $latest_tag != $package_tag
          echo $"new_version=($new_version)" | save --append $env.GITHUB_OUTPUT

  release:
    runs-on: ubuntu-latest
    needs: check_new_version
    if: ${{ needs.check_new_version.outputs.new_version }}
    steps:
      - name: Release
        run: echo "new release will be here"
